### ISSUE TITLE
Allow OP_RETURN transactions

### ISSUE THREAD

**Issue by kosinusbch** [gatewaycash/gateway#30]
This and a custom address fields are the the two hands down most important features for gateway button to be a drop-in replacement for moneybutton.

**Comment by ty-everett** [comment]
I intend to get this in within the next week, working on some structural changes to the code base, native currency support and then will be adding this.

**Comment by kosinusbch** [comment]
@ty-everett I think it should be up to the individual website to add the op_return data, so we keep the input boxes to a minimal in the popup itself. If the user needs to modify this, the website will allow them to.

I'm not sure what the best option for achieving this is, whether you copy MB's way of doing it, or add a special op return option to the button, but whatever you do it needs to be able to have more than one op pushdata, so we can use this to interact with apps like memo or other projects that need a MB replacement.

**Comment by ty-everett** [comment]
I think an external website can build this with Gateway. We don't want this on the "base layer" as it were, since it would increase bundle size a lot to build into the core JS bundle for PayButton.

It's very possible to make social media platforms with this:

[Gateway Doc](https://docs.google.com/document/d/16oypfFXaJqBoHK3C-KLucZNGA-l56jsR8SpqoZAcPXA/edit?usp=sharing)

(use-cases section)

**Comment by ty-everett** [comment]
I'm going to close this for now but I'd love to see projects use PayButton for this, I might start one myself over at a new version of [unite.cash](https://unite.cash/) if I ever get the time.
