### ISSUE TITLE
.render() doesn't seem to support being ran again on the same element

### ISSUE THREAD

**Issue by Klakurka** [gatewaycash/gateway#63]
.render() doesn't seem to support being ran again on the same element multiple times.

The button will render once, but subsequent calls of .render() don't update the button.

**Comment by ty-everett** [comment]
I think we can do a fix for this by adding an `id` prop to the props list, and assigning the outermost React element (the encapsulating div) with that `id`. The `id` can be assigned from the element at initial render-time so that it persists and it will find the `id` upon subsequent renders.

The only problem is that the exact, specific *element* returned from `document.getElementById()` can't be used twice, so you would need to query the DOM for the new element at each render.

**Comment by ty-everett** [comment]
Actually, that sounds like a silly restriction to have. How about we change the function signature to:

```
window.PayButton.render(elementID, props);
```

Where `elementID` is a string containing the ID of the element, and props is the properties object.

Would that break your use-case at all? If we were to do that everything would be handled automatically and the same element could be used multiple times without any extra work.

**Comment by Klakurka** [comment]
That will work fine if it fixes the issue.

**Comment by Klakurka** [comment]
Fixed the ID, that was the problem there.

It still doesn't seem to want to run more than once though. No errors but it doesn't populate the div:

`PayButton.render('paymentButton', {
	buttonText: 'Pay with Bitcoin Cash ($120)',
	dialogTitle: 0,
	amount: 120,
	currency: 'USD',
	merchantID: 'myID',
	paymentCompleteCallback: "processPayment()",
	closeWhenComplete: true
});`

Any ideas?

**Comment by Klakurka** [comment]
Looks good!

We'll let you know if we run into any other issues.
